### ISSUE TITLE
split into two packages?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/boost-feedstock#95] opened 2020-09-22 03:12 UTC
The boost headers are about 169 MB extracted. Seems a little silly to have them installed. That said, I understand that this kind of optimization is not something that was in the ethos of conda.

I just wanted to flag this.

**Comment by isuruf** [comment] 2020-09-22 03:13
Duplicate of https://github.com/conda-forge/boost-cpp-feedstock/issues/83

**Closed by isuruf** 2020-09-22 03:13 UTC
